# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
    version: @project.version@
#    security:
    user:
      name: tht
      password: tht
  elasticsearch:
    rest:
      uris:
        #        - 192.168.68.129:9200
        #        - 192.168.68.130:9200
        #        - 192.168.68.131:9200
         127.0.0.1:9200
      username:
      password:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ry-vue?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
#    host: 192.168.160.128
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    listener:
      direct:
        auto-startup: false
      simple:
        auto-startup: false
      stream:
        auto-startup: false


rabbitmq:
  start: false
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.**.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# redis 配置
redis:
  # 地址
  host: localhost
  # 端口，默认为6379
  port: 6379
  # 数据库索引
  database: 0
  # 密码
  password:
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms

# 日志配置
logging:
  config: classpath:logback-spring.xml
  # 这边覆盖了配置文件的配置，规范就在一个地方配置
#  level:
#    com.example: debug
#    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
name: ${name}